name: l10n_key_preview
description: preview l10n keys in Dart code
version: 0.1.0
homepage: https://github.com/tks-00/l10n_key_preview
repository: https://github.com/tks-00/l10n_key_preview

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.0.0
  build: ^2.4.0
  source_span: ^1.10.0
  source_gen: ^1.5.0 # コード生成ユーティリティ
  glob: ^2.1.2 # ファイルパターンマッチング
  path: ^1.8.3 # パス操作ユーティリティ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  lints: ^5.1.1
  test: ^1.24.0

flutter:
